---
title: lebudo
timezone: Europe/Helsinki
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
links:
-
  text: Peruskurssi
  hash: peruskurssi
-
  text: Harjoitusajat
  hash: harjoitusajat
-
  text: Seura
  hash: seura
-
  text: Dojo
  hash: dojo
permalink: none
exclude:
- Gemfile
- Gemfile.lock
