---
title: lebudo
timezone: Europe/Helsinki
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: none
exclude:
- Gemfile
- Gemfile.lock
