---
title: Lebudo
timezone: Europe/Helsinki
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
